name: A21s Ultimate ROM Builder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Cleanup and Maximize Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" /usr/local/lib/android
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl git wget python3
          echo "Space is ready for the giant build!"

      - name: 2. Set Up Git Identity
        run: |
          git config --global user.name "ABD99897"
          git config --global user.email "test@test.com"
          git config --global color.ui false

      - name: 3. Install Repo Tool
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: 4. Initialize ROM Source (DerpFest 13)
        run: |
          mkdir ~/rom
          cd ~/rom
          repo init -u https://github.com/DerpFest-AOSP/manifest -b 13 --depth=1
          echo "Source Initialized!"

      - name: 5. Sync Heavy Files (This takes time)
        run: |
          cd ~/rom
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          echo "Source Synced Successfully!"

      - name: 6. Clone A21s Device Trees
        run: |
          cd ~/rom
          git clone https://github.com/TDD788/A21s-DevTree device/samsung/a21s
          git clone https://github.com/TDD788/A21s-Vendor vendor/samsung/a21s
          git clone https://github.com/TDD788/A21s-Kernel kernel/samsung/a21s

      - name: 7. The Grand Finale (Building the ROM)
        run: |
          cd ~/rom
          . build/envsetup.sh
          lunch derp_a21s-userdebug
          mka bacon -j$(nproc --all)

      - name: 8. Upload the Final Result
        uses: actions/upload-artifact@v4
        with:
          name: DerpFest-A21s-Final
          path: ~/rom/out/target/product/a21s/*.zip
